# configs/defaults/account.yaml
# デフォルトのアカウント設定

genre: 'product' # 商品紹介・お買い物
locale: 'ja-JP'
posting:
  time_window: ['09:00', '11:00']
  days: [Mon, Tue, Wed, Thu, Fri]
ai:
  provider: 'openrouter'
  model: 'deepseek/deepseek-chat-v3.1:free'
  temperature: 0.7
  max_tokens: 1200
note:
  login_method: 'email_password'
  cookie_secret_name: 'NOTE_COOKIE'
sheets:
  enabled: true
  doc_id: ''
  worksheet: 'posts'
overrides:
  seasonal_topic: '商品紹介・お買い物'
  tags:
    [
      '#お買い物',
      '#商品紹介',
      '#おすすめ',
      '#レビュー',
      '#お得情報',
      '#ショッピング',
      '#PR',
    ]
